In [ ]:
#计算图是现代深度学习框架的核心
#手动求取反向传播废时费力，而且容易出错
#autograd.Variable封装了data,grad,grad_fn三个数据
#data是tensor，grad的形状与data一致，grad_fn指向一个Func记录操作历史

#可选参数
#requires_grad(bool):是否对该ariable求导数
#volatile(bool):设置为True，构建在该variable上的图都不会求道，为推理阶段设计


In [2]:
import torch as t
from torch.autograd import Variable as var

#从tensor中创建var，指定需要求导
a = var(t.ones(3,4),requires_grad = True)
b = var(t.zeros(3,4))
print(a)
print(b)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], requires_grad=True)
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [ ]:
c = a+b
print(c)
c = a.add(b)
print(c)
#上面两种方法一样结果

In [ ]:
d = c.sum()
d.backward()#反向传播

In [ ]:
#注意区别，第一种因为先取了data部分再sum，所以数据类型是tensor
c.data.sum()
#第二种因为直接sum,所以数据类型仍然为var
c.sum()

In [3]:
#例子求y=x^2 * e^x的导数
x = var(t.randn(3,4),requires_grad=True)

def f(x):
    '''定义y'''
    y = x**2 * t.exp(x)
    return y

y = f(x)

def gradf(x):
    '''手动求导'''
    dx = 2*x*t.exp(x) +x**2*t.exp(x)
    return dx

In [4]:
print("手动求导数:")
dx = gradf(x)
print(dx)
y.backward(t.ones(y.size()))#确保grad_var的形状与y一样
print("自动求导数：")  
x.grad

手动求导数:
tensor([[ 2.4460e+00,  1.6331e+00, -4.0214e-01,  3.0908e+01],
        [ 2.1939e+00,  5.3760e-01,  2.3291e-02,  2.4220e+01],
        [-4.1649e-01, -4.3951e-01, -2.1646e-01,  5.1797e+00]],
       grad_fn=<AddBackward0>)
自动求导数：


tensor([[ 2.4460e+00,  1.6331e+00, -4.0214e-01,  3.0908e+01],
        [ 2.1939e+00,  5.3760e-01,  2.3291e-02,  2.4220e+01],
        [-4.1649e-01, -4.3951e-01, -2.1646e-01,  5.1797e+00]])