In [2]:
import torch as t
#_是inplace的调用方式，会修改自己读书数据例如a_.add(b)会导致a的值改变
#Tensor和numpy用法很像

In [30]:
#Tensor的创建

#a的值是随机值
print(t.Tensor(2,3))

#确定矩阵的值
print(t.Tensor([[1,2,3],[4,5,6]]))

#全1矩阵
print(t.ones(2,3))

#全0矩阵
print(t.zeros(2,3))

#步长生成
print(t.arange(1,9,2))

#线性平分
print(t.linspace(1,10,3))

#随机数列
print(t.randn(2,3))

#对角线为1
print(t.eye(4,5))

tensor([[2.0690e+31, 3.0949e-41, 2.0383e+31],
        [3.0949e-41, 1.4013e-45, 3.0949e-41]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([1, 3, 5, 7])
tensor([ 1.0000,  5.5000, 10.0000])
tensor([[-1.8627, -0.1912, -0.0964],
        [-1.3466, -1.2364, -0.3953]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]])


In [31]:
#将tensor转成lists
b.tolist()
#查看tenosr的尺寸
print( b.size() )
print( b.shape )
print( b.numel() )

torch.Size([2, 3])
torch.Size([2, 3])
6


In [59]:
#形状变换
a=t.arange(0,6)
b=t.Tensor([[1,2,3],[4,5,6]])
print(a)

#二维固定转换
print(a.view(2,3))

#单一固定
print(a.view(-1,3))

#把数组增加一个维度
print(b.unsqueeze(0).size())
print(b.squeeze(0).size())

tensor([0, 1, 2, 3, 4, 5])
tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1, 2],
        [3, 4, 5]])
torch.Size([1, 2, 3])
torch.Size([2, 3])


In [62]:
#resize()和view()不同，resize可以改变出比原来尺寸大或者小的矩阵
#且变成更小的以后，原来的还是保存着的。
print(b.resize_(1,3))
print(b.resize_(3,4))

tensor([[1., 2., 3.]])
tensor([[1.0000e+00, 2.0000e+00, 3.0000e+00, 4.0000e+00],
        [5.0000e+00, 6.0000e+00, 4.2039e-45, 0.0000e+00],
        [5.6052e-45, 0.0000e+00, 7.0065e-45, 0.0000e+00]])
