In [1]:
import torch as t
#_是inplace的调用方式，会修改自己读书数据例如a_.add(b)会导致a的值改变
#Tensor和numpy用法很像

In [2]:
#Tensor的创建

#a的值是随机值
print(t.Tensor(2,3))

#确定矩阵的值
print(t.Tensor([[1,2,3],[4,5,6]]))

#全1矩阵
print(t.ones(2,3))

#全0矩阵
print(t.zeros(2,3))

#步长生成
print(t.arange(1,9,2))

#线性平分
print(t.linspace(1,10,3))

#随机数列
print(t.randn(2,3))

#对角线为1
print(t.eye(4,5))

tensor([[2.5783e-09, 3.1816e+12, 2.7096e-09],
        [2.6409e-06, 1.0257e-08, 1.2823e+16]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([1, 3, 5, 7])
tensor([ 1.0000,  5.5000, 10.0000])
tensor([[ 0.1058,  0.0473,  0.0522],
        [ 1.4934,  0.1200, -1.1571]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]])


In [5]:
#将tensor转成lists
b.tolist()
#查看tenosr的尺寸
print( b.size() )
print( b.shape )
print( b.numel() )

torch.Size([2, 3])
torch.Size([2, 3])
6


In [6]:
#形状变换
a=t.arange(0,6)
b=t.Tensor([[1,2,3],[4,5,6]])
print(a)

#二维固定转换
print(a.view(2,3))

#单一固定
print(a.view(-1,3))

#把数组增加一个维度
print(b.unsqueeze(0).size())
print(b.squeeze(0).size())

tensor([0, 1, 2, 3, 4, 5])
tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1, 2],
        [3, 4, 5]])
torch.Size([1, 2, 3])
torch.Size([2, 3])


In [7]:
#resize()和view()不同，resize可以改变出比原来尺寸大或者小的矩阵
#且变成更小的以后，原来的还是保存着的。
print(b.resize_(1,3))
print(b.resize_(3,4))

tensor([[1., 2., 3.]])
tensor([[1., 2., 3., 4.],
        [5., 6., 1., 0.],
        [0., 0., 0., 0.]])


In [8]:
#设置默认Tensor格式
t.set_default_tensor_type('torch.FloatTensor')
#还有ByteTensor\Char\Short\Int型，转换成CUDA只需要 torch.cuda.类型

In [9]:
#常见逐元素操作命令
#abs/sqrt/div/exp/fmod取余/log/pow
#cos/sin/asin/atan2/cosh
#ceil上取整/round四舍五入/floor下取整/trunc取正数部分
#clamp(input,min,max)超过min max截断
#sigmod/tanh激活函数

In [10]:
#常见的归并操作
#mean/sum/median/mode众数
#norm范数/dist距离
#std标准差/var方差
#cumsum累加/cumprob累乘

In [11]:
#常见的线性代数函数
#trace对角线之和
#diag对角线元素
#triu/tril矩阵的上三角/下三角
#mm/bmm 矩阵乘法/batch的矩阵乘法
#addmm/addbmm/addmv
#t转制
#dot/cross内积/外积
#inverse求逆矩阵
#svd奇异值分解

In [12]:
#numpy-->Tensor 由此可借用numpy中的算法，开销很小
import numpy as np
a = np.ones([2,3])
#trans by 
b=t.from_numpy(a)
#or
b=t.Tensor(a)

In [13]:
#其他需要注意的地方
#持久化
if t.cuda.is_available():
    a=a.cuda(1)
    t.save(a,'a.pth')
    
    b=t.load('a.pth')
#向量化！！！
#如果直接使用c++风格的运算，比内建函数相差速度近10倍。因此尽量使用内建函数