In [1]:
#虽然有auto_grad可以使用，但是如果要只用手写则工作量会巨大
#torch.nn的核心数据结构是module，可以表示一个层也可以表示很多层组成的网络

In [20]:
#实现全连接层 y=Wx+B
import torch as t
import torch.nn as nn
from torch.autograd import variable as var

class Linear(nn.Module):#从nn继承
    def __init__(self,in_features,out_features):
        nn.Module.__init__(self) #或者snn.Module.__init_(self) #或者uper(Linear,self).__init__()
        #在自己构造的函数中自己定nn.Module.__init_(self) #或者义可学习的参数，并封装成Paramters
        #parameters是一种特殊的variable，其默认是可以求导
        self.w = nn.Parameter(t.randn(in_features,out_features))
        self.b = nn.Parameter(t.randn(out_features))
        
    def forward(self,x):
        x = x.mm(self.w)
        return x + self.b.expand_as(x) #expand是把前面的tensor变成和后面x形状一样的tensor
    #在写的时候不用写backward，因为nn模块可以使用autograd自动求

In [25]:
layer = Linear(4,3)
inputs = var(t.randn(2,4))
output = layer(inputs)
output

tensor([[-3.9919, -2.2863, -7.5598],
        [ 1.6921, -0.7332, -0.7921]], grad_fn=<AddBackward0>)

In [27]:
#Module模块中，可以使用named_parameters或者parameter返回迭代其，前者会给每个参数加上名字
for name,parameter in layer.named_parameters():
    print(name,parameter)

w Parameter containing:
tensor([[ 0.5674, -0.9214,  0.4878],
        [ 0.8759, -1.9884, -0.4471],
        [-1.4719, -1.4856, -1.8592],
        [ 0.7325,  0.3287,  1.8842]], requires_grad=True)
b Parameter containing:
tensor([ 0.5895,  0.7750, -0.3620], requires_grad=True)


In [29]:
#多层感知机的实现，两层全连接，使用sigmoid激活函数
class Perceptron(nn.Module):
    def __init__(self,input_features,hidden_features,output_features):
        nn.Module.__init__(self)
        self.layer1 = Linear(input_features,hidden_features)
        self.layer2 = Linear(hidden_features,output_features)
        
    def forward(self,x):
        x = layer1(x)
        x = t.sigmoid(x)
        x = layer2(x)
        return x

In [36]:
perceptron = Perceptron(3,4,1)#仅仅是例子
for name,param in perceptron.named_parameters():#注意括号
    print (name,param.size())

layer1.w torch.Size([3, 4])
layer1.b torch.Size([4])
layer2.w torch.Size([4, 1])
layer2.b torch.Size([1])
